
package views;

import controllers.LoginController;


public class LoginJFrame extends javax.swing.JFrame {

    /**
     * Creates new form LoginJFrame
     */
    public LoginJFrame() {
        initComponents();
        //Icon
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/images/iconapp.png")));
        //Them coltroller
        LoginController controller = new LoginController(this, jbtnLogin, jtfUserName, jpfPassword, jlbLoginMessage);
        controller.setEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnLogin = new javax.swing.JPanel();
        jpnLoginTitle = new javax.swing.JPanel();
        jlbLoginTitle = new javax.swing.JLabel();
        jpnLoginInfo = new javax.swing.JPanel();
        jpnUserName = new javax.swing.JPanel();
        jlbUserName = new javax.swing.JLabel();
        jtfUserName = new javax.swing.JTextField();
        jpnPassword = new javax.swing.JPanel();
        jpfPassword = new javax.swing.JPasswordField();
        jpnLoginBTN = new javax.swing.JPanel();
        jlbLoginMessage = new javax.swing.JLabel();
        jbtnLogin = new javax.swing.JButton();
        jlbPassword = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Đăng nhập");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jpnLogin.setBackground(new java.awt.Color(255, 255, 255));
        jpnLogin.setPreferredSize(new java.awt.Dimension(400, 400));

        jpnLoginTitle.setBackground(new java.awt.Color(255, 255, 255));

        jlbLoginTitle.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jlbLoginTitle.setForeground(new java.awt.Color(0, 51, 255));
        jlbLoginTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbLoginTitle.setText("ĐIỆN LỰC BẮC TỪ LIÊM");
        jlbLoginTitle.setToolTipText("");

        javax.swing.GroupLayout jpnLoginTitleLayout = new javax.swing.GroupLayout(jpnLoginTitle);
        jpnLoginTitle.setLayout(jpnLoginTitleLayout);
        jpnLoginTitleLayout.setHorizontalGroup(
            jpnLoginTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnLoginTitleLayout.setVerticalGroup(
            jpnLoginTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbLoginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addContainerGap())
        );

        jlbLoginTitle.getAccessibleContext().setAccessibleName("ĐIỆN LỰC BẮC TỪ LIÊM");

        jpnLoginInfo.setBackground(new java.awt.Color(255, 255, 255));

        jpnUserName.setBackground(new java.awt.Color(255, 255, 255));

        jlbUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbUserName.setText("Tài khoản");
        jlbUserName.setPreferredSize(new java.awt.Dimension(300, 20));

        jtfUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtfUserName.setPreferredSize(new java.awt.Dimension(300, 30));

        javax.swing.GroupLayout jpnUserNameLayout = new javax.swing.GroupLayout(jpnUserName);
        jpnUserName.setLayout(jpnUserNameLayout);
        jpnUserNameLayout.setHorizontalGroup(
            jpnUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUserNameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jpnUserNameLayout.setVerticalGroup(
            jpnUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnUserNameLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jpnUserNameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfUserName, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jlbUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jpnPassword.setBackground(new java.awt.Color(255, 255, 255));

        jpfPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpfPassword.setPreferredSize(new java.awt.Dimension(300, 30));

        javax.swing.GroupLayout jpnPasswordLayout = new javax.swing.GroupLayout(jpnPassword);
        jpnPassword.setLayout(jpnPasswordLayout);
        jpnPasswordLayout.setHorizontalGroup(
            jpnPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPasswordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jpnPasswordLayout.setVerticalGroup(
            jpnPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPasswordLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jpnLoginBTN.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnLoginBTNLayout = new javax.swing.GroupLayout(jpnLoginBTN);
        jpnLoginBTN.setLayout(jpnLoginBTNLayout);
        jpnLoginBTNLayout.setHorizontalGroup(
            jpnLoginBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        jpnLoginBTNLayout.setVerticalGroup(
            jpnLoginBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 42, Short.MAX_VALUE)
        );

        jlbLoginMessage.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jlbLoginMessage.setForeground(new java.awt.Color(255, 0, 0));
        jlbLoginMessage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbLoginMessage.setText("Vui lòng nhập thông tin đăng nhập!");

        jbtnLogin.setBackground(new java.awt.Color(204, 204, 204));
        jbtnLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtnLogin.setText("Đăng Nhập");
        jbtnLogin.setPreferredSize(new java.awt.Dimension(300, 25));

        jlbPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jlbPassword.setText("Mật khẩu");
        jlbPassword.setPreferredSize(new java.awt.Dimension(300, 20));

        javax.swing.GroupLayout jpnLoginInfoLayout = new javax.swing.GroupLayout(jpnLoginInfo);
        jpnLoginInfo.setLayout(jpnLoginInfoLayout);
        jpnLoginInfoLayout.setHorizontalGroup(
            jpnLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnLoginInfoLayout.createSequentialGroup()
                .addGroup(jpnLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jpnUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnLoginInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jlbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnLoginInfoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jpnLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlbLoginMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnLoginInfoLayout.setVerticalGroup(
            jpnLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoginInfoLayout.createSequentialGroup()
                .addGroup(jpnLoginInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnLoginInfoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jpnUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpnPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnLoginInfoLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jlbPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jlbLoginMessage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnLoginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout jpnLoginLayout = new javax.swing.GroupLayout(jpnLogin);
        jpnLogin.setLayout(jpnLoginLayout);
        jpnLoginLayout.setHorizontalGroup(
            jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnLoginTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnLoginInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );
        jpnLoginLayout.setVerticalGroup(
            jpnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnLoginTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnLoginInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jpnLogin, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JLabel jlbLoginMessage;
    private javax.swing.JLabel jlbLoginTitle;
    private javax.swing.JLabel jlbPassword;
    private javax.swing.JLabel jlbUserName;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JPanel jpnLogin;
    private javax.swing.JPanel jpnLoginBTN;
    private javax.swing.JPanel jpnLoginInfo;
    private javax.swing.JPanel jpnLoginTitle;
    private javax.swing.JPanel jpnPassword;
    private javax.swing.JPanel jpnUserName;
    private javax.swing.JTextField jtfUserName;
    // End of variables declaration//GEN-END:variables
}
